### ISSUE TITLE
Creación de componente de importación de frames

### ISSUE THREAD

**Issue by angellinares** [Fablab-Sevilla/GH2SAP#2]
1. Creación de componente de importación de frames a través de líneas.
   - Se establecerá una estructura base que permita posteriormente eliminar elementos fijados para comprobar su funcionamiento e implementar nuevas opciones (selección de perfil, ...).
   - El componente será funcional sin necesidad de especificar los datos anteriormente fijados y permitirá importar las barras en SAP2000.

Nota: tengo la duda de si debemos crear los frames a través de los puntos de sus extremos o a través de un elemento línea.

**Comment by evvicente** [comment]
En mi opinión es mas práctico asignarlo a un elemento línea.

**Comment by angellinares** [comment]
@evvicente, parece lo lógico. Procedamos así pues.

**Comment by evvicente** [comment]
Creada la primera versión funcional.
Al no estar creada la rutina que genere las secciones de barras el programa no reconoce el nombre de sección del input. Es necesario generar la rutina de creación de sección y correrla previamente.
